const data = ({ height, ne_top, htec_max, day, year, month, long, lat }) => {
  console.log(ne_top);
  return {
    model: 'iri2016',
    year: year,
    month: month,
    day: day,
    time_flag: '1',
    hour: '',
    geo_flag: '1.',
    latitude: lat,
    longitude: long,
    height: height,
    profile: '8',
    start: '0',
    stop: '23.99',
    step: '0.25',
    sun_n: '',
    ion_n: '',
    radio_f: '',
    radio_f81: '',
    htec_max: htec_max,
    ne_top: ne_top,
    imap: '0.',
    ffof2: '0.',
    hhmf2: '0.',
    ib0: '2.',
    probab: '0.',
    fauroralb: '0.',
    ffoE: '1.',
    dreg: '0.',
    tset: '2.',
    icomp: '0.',
    nmf2: '0.',
    hmf2: '0.',
    nme: '0.',
    user_hme: '0.',
    user_B0: '0.',
    vars: ['00', '03', '04', '29'],
    format: '2',
    linestyle: 'solid',
    charsize: '',
    symbol: '2',
    symsize: '',
    yscale: 'Linear',
    xscale: 'Linear',
    imagex: '640',
    imagey: '480',
  };
};

module.exports = data;
